FROM openjdk:11 as builder

WORKDIR /payara

# perform layer caching of dependencies
COPY gradle/ ./gradle/
COPY gradlew ./
COPY build.gradle ./
COPY settings.gradle ./
RUN ./gradlew --no-daemon dependencies

# build the war artifact
COPY src/ src/
RUN ./gradlew --no-daemon assemble

FROM gcr.io/distroless/java:11

COPY --from=amd64/busybox:1.31.1 /bin/busybox /busybox/busybox
RUN ["/busybox/busybox", "--install", "/bin"]

WORKDIR /payara

EXPOSE 8080 9090

ENTRYPOINT ["java", "-server", "-Xshare:on", "-XX:SharedArchiveFile=payara.jsa", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=50.0", "-XX:ThreadStackSize=256", "-XX:MaxMetaspaceSize=128m", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=250", "-XX:+UseStringDeduplication", "-Djava.security.egd=file:/dev/./urandom", "-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.port=9090", "-Djava.rmi.server.hostname=localhost", "-Dcom.sun.management.jmxremote.rmi.port=9090", "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.authenticate=false", "-jar", "micro-root/launch-micro.jar"]
CMD ["--nocluster", "--disablephonehome"]

ENV APPCDS_ENABLED=true

COPY --from=payara/micro:5.201 /opt/payara/payara-micro.jar ./
COPY --from=builder /payara/build/libs/payara-micro-appcds.war ./

# https://blog.payara.fish/warming-up-payara-micro-container-images-in-5.201
RUN java -jar payara-micro.jar --rootdir micro-root --outputlauncher && \
    rm -rf payara-micro.jar && \
    java -XX:DumpLoadedClassList=classes.lst -jar micro-root/launch-micro.jar --deploy payara-micro-appcds.war:/ --warmup && \
    java -Xshare:dump -XX:SharedClassListFile=classes.lst -XX:SharedArchiveFile=payara.jsa -jar micro-root/launch-micro.jar && \
    rm -rf classes.lst payara-micro-appcds.war